name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.12'

        - name: Install dependencies
          run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

        - name: Prepare SSH key
          run: |
                echo "$EC2_SSH_KEY" > ec2_key.pem
                chmod 600 ec2_key.pem
          env:
            EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

        - name: Pause service on EC2
          run: |
                ssh -o StrictHostKeyChecking=no -i ec2_key.pem \
                  ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
                    sudo systemctl stop ${{ secrets.SERVICE_NAME }}
                EOF

        - name: Copy source code to EC2
          run: |
                rsync -avz -e "ssh -o StrictHostKeyChecking=no -i ec2_key.pem" \
                  ./ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/app

        - name: Install dependencies on EC2
          run: |
                ssh -o StrictHostKeyChecking=no -i ec2_key.pem \
                  ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
                    cd ~/app
                    source venv/bin/activate
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt
                EOF
                
        - name: Restart Service on EC2
          run: |
            ssh -o StrictHostKeyChecking=no -i ec2_key.pem \
              ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
                sudo systemctl start ${{ secrets.SERVICE_NAME }}
            EOF
          